"use client";
/* eslint-disable @next/next/no-img-element, jsx-a11y/media-has-caption, jsx-a11y/no-static-element-interactions */
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import type { AuthorizedUser } from "@/lib/auth";
import type { Category, ContentItem, ContentType, MediaItem, Tag } from "@/lib/types";
import { slugify } from "@/lib/validation";
import { VisualController } from "./visual-controller";
import { SettingsManager } from "./settings-manager";

type Section="dashboard"|"content"|"media"|"taxonomy"|"design"|"settings"|"users";
type Dashboard={counts:Array<{type:string;status:string;total:number}>;activity:Array<{id:number;action:string;entityType:string;detail:string;createdAt:string;userName?:string}>};
type Initial={items:ContentItem[];categories:Category[];tags:Tag[];media:MediaItem[];dashboard:Dashboard;settings:Record<string,unknown>};
const blank=():Partial<ContentItem>&{tagIds:number[]}=>({type:"article",title:"",slug:"",subtitle:"",excerpt:"",bodyHtml:"<p>Start writing here…</p>",status:"draft",categoryId:null,featuredImageId:null,socialImageId:null,featured:false,galleryJson:"[]",fieldsJson:"{}",seoTitle:"",seoDescription:"",tagIds:[]});
const labels:Record<ContentType,string>={article:"Articles",note:"Notes",film:"Films",place:"Places"};

export function AdminClient({initial,user,signOutPath}:{initial:Initial;user:AuthorizedUser;signOutPath:string}){
  const [data,setData]=useState(initial);const [section,setSection]=useState<Section>("dashboard");const [editor,setEditor]=useState<ReturnType<typeof blank>|null>(null);const [query,setQuery]=useState("");const [typeFilter,setTypeFilter]=useState<"all"|ContentType>("all");const [status,setStatus]=useState("");
  async function refresh(){const r=await fetch("/api/admin/content");const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}
  const counts=useMemo(()=>Object.fromEntries(data.dashboard.counts.map(c=>[`${c.type}:${c.status}`,Number(c.total)])),[data.dashboard]);
  const published=data.dashboard.counts.filter(c=>c.status==="published").reduce((n,c)=>n+Number(c.total),0);const drafts=data.dashboard.counts.filter(c=>c.status==="draft").reduce((n,c)=>n+Number(c.total),0);
  function openItem(item?:ContentItem){setEditor(item?{...item,featured:Boolean(item.featured),tagIds:(item.tags??[]).map(t=>t.id)}:blank());setSection("content")}
  return <div className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" href="/">✦ KNOW NOTHING DAILY</Link><div className="admin-label">WORKSPACE</div><nav>{([['dashboard','Dashboard'],['content','Content'],['media','Media library'],['taxonomy','Categories & tags'],['design','Website design'],['settings','Settings'],['users','Users']] as [Section,string][]).map(([id,label])=>(id!=="users"||user.role==="admin")&&<button className={section===id?"active":""} onClick={()=>{setSection(id);setEditor(null)}} key={id}>{icon(id)}<span>{label}</span></button>)}</nav><div className="admin-account"><div className="avatar">{user.displayName.slice(0,1).toUpperCase()}</div><div><strong>{user.displayName}</strong><span>{user.role}</span></div><a href={signOutPath} aria-label="Sign out">↗</a></div></aside>
    <main className="admin-main"><header className="admin-topbar"><div><span className="crumb">CMS / {section.toUpperCase()}</span><h1>{section==="taxonomy"?"Categories & tags":section[0].toUpperCase()+section.slice(1)}</h1></div><div className="top-actions"><a href="/" target="_blank">View site ↗</a><button className="primary" onClick={()=>openItem()}>+ New content</button></div></header>
    {status&&<div className="admin-toast" role="status">{status}</div>}
    {section==="dashboard"&&<DashboardView items={data.items} counts={{published,drafts,articles:(counts["article:published"]??0)+(counts["article:draft"]??0),notes:(counts["note:published"]??0)+(counts["note:draft"]??0),films:(counts["film:published"]??0)+(counts["film:draft"]??0),places:(counts["place:published"]??0)+(counts["place:draft"]??0)}} activity={data.dashboard.activity} openItem={openItem}/>} 
    {section==="content"&&(editor?<Editor item={editor} setItem={setEditor} data={data} onDone={async(message)=>{setStatus(message);await refresh();setEditor(null)}}/>:<ContentManager items={data.items} query={query} setQuery={setQuery} typeFilter={typeFilter} setTypeFilter={setTypeFilter} openItem={openItem} onDelete={async(id)=>{if(!confirm("Delete this content permanently?"))return;const r=await fetch(`/api/admin/content/${id}`,{method:"DELETE"});const j=await r.json();setStatus(r.ok?"Content deleted.":j.error);if(r.ok)await refresh()}}/>)}
    {section==="media"&&<MediaManager media={data.media} onChange={async(message)=>{setStatus(message);await refresh()}}/>}
    {section==="taxonomy"&&<TaxonomyManager categories={data.categories} tags={data.tags} onChange={async(message)=>{setStatus(message);await refresh()}}/>}
    {section==="design"&&<VisualController settings={data.settings} media={data.media} canEdit={user.role==="admin"} onSaved={async()=>{setStatus("Website design saved.");await refresh()}}/>}
    {section==="settings"&&<SettingsManager settings={data.settings} media={data.media} canEdit={user.role==="admin"} onSaved={async()=>{setStatus("Settings saved.");await refresh()}}/>}
    {section==="users"&&user.role==="admin"&&<UsersManager/>}
    </main></div>
}

function DashboardView({items,counts,activity,openItem}:{items:ContentItem[];counts:Record<string,number>;activity:Dashboard["activity"];openItem:(item:ContentItem)=>void}){return <div className="admin-content"><div className="metric-grid">{[["Published",counts.published,"Live in the archive"],["Drafts",counts.drafts,"Waiting for attention"],["Articles",counts.articles,"Long-form stories"],["Notes",counts.notes,"Small discoveries"],["Films",counts.films,"Screen archive"],["Places",counts.places,"Field notes"]].map(([label,value,note])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div><div className="dashboard-grid"><section className="admin-panel"><div className="panel-head"><h2>Recent content</h2><button onClick={()=>openItem(items[0])}>Open latest ↗</button></div><AdminTable items={items.slice(0,6)} openItem={openItem}/></section><section className="admin-panel activity"><div className="panel-head"><h2>Recent activity</h2></div>{activity.length?activity.map(a=><div className="activity-row" key={a.id}><span>{a.action}</span><div><strong>{a.detail}</strong><small>{a.userName??"System"} · {new Date(a.createdAt).toLocaleDateString()}</small></div></div>):<p className="muted">Activity will appear as the archive is edited.</p>}</section></div></div>}

function ContentManager({items,query,setQuery,typeFilter,setTypeFilter,openItem,onDelete}:{items:ContentItem[];query:string;setQuery:(s:string)=>void;typeFilter:"all"|ContentType;setTypeFilter:(v:"all"|ContentType)=>void;openItem:(i:ContentItem)=>void;onDelete:(id:number)=>void}){const filtered=items.filter(i=>(typeFilter==="all"||i.type===typeFilter)&&(`${i.title} ${i.excerpt}`.toLowerCase().includes(query.toLowerCase())));return <div className="admin-content"><div className="manager-tools"><label className="admin-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search all content…"/></label><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value as typeof typeFilter)}><option value="all">All types</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><section className="admin-panel"><AdminTable items={filtered} openItem={openItem} onDelete={onDelete}/></section></div>}
function AdminTable({items,openItem,onDelete}:{items:ContentItem[];openItem:(i:ContentItem)=>void;onDelete?:(id:number)=>void}){return <div className="admin-table"><div className="table-row table-head"><span>Title</span><span>Type</span><span>Status</span><span>Updated</span><span></span></div>{items.map(i=><div className="table-row" key={i.id}><button className="title-cell" onClick={()=>openItem(i)}><strong>{i.title}</strong><small>/{i.slug}</small></button><span>{labels[i.type]}</span><span className={`status-chip ${i.status}`}>{i.status}</span><time>{new Date(i.updatedAt).toLocaleDateString()}</time><div className="row-actions"><button onClick={()=>openItem(i)}>Edit</button>{onDelete&&<button className="danger" onClick={()=>onDelete(i.id)}>Delete</button>}</div></div>)}</div>}

function Editor({item,setItem,data,onDone}:{item:ReturnType<typeof blank>;setItem:(v:ReturnType<typeof blank>)=>void;data:Initial;onDone:(message:string)=>Promise<void>}){
  // "Featured image/video only" is kept separate from repeatable body media as the article cover.
  const rich=useRef<HTMLDivElement>(null);const savedRange=useRef<Range|null>(null);const [saving,setSaving]=useState(false);const [uploadingMedia,setUploadingMedia]=useState(false);const [editorMedia,setEditorMedia]=useState(data.media.filter(media=>/^(image|video)\//.test(media.mimeType)));const [bodyMediaId,setBodyMediaId]=useState<number|null>(null);const [mediaPlacement,setMediaPlacement]=useState<"cursor"|"top"|"after-first"|"bottom">("cursor");const [dirty,setDirty]=useState(false);const [specific,setSpecific]=useState<Record<string,string>>(()=>{try{return JSON.parse(item.fieldsJson??"{}")}catch{return {}}});
  function patch(key:string,value:unknown){setItem({...item,[key]:value});setDirty(true)}
  // The draft debounce intentionally resets whenever the current editor snapshot changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!dirty||!item.id||item.status!=="draft")return;const timer=setTimeout(()=>save("draft",true),2500);return()=>clearTimeout(timer)},[dirty,item]);
  async function save(nextStatus=item.status??"draft",autosave=false){setSaving(true);const payload={...item,slug:slugify(item.title??""),status:nextStatus,bodyHtml:rich.current?.innerHTML??item.bodyHtml,fieldsJson:JSON.stringify(specific),tagIds:item.tagIds};const r=await fetch(item.id?`/api/admin/content/${item.id}`:"/api/admin/content",{method:item.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setSaving(false);if(!r.ok){alert(j.error);return}setDirty(false);if(autosave){setItem({...item,...j.item,tagIds:item.tagIds});return}await onDone(nextStatus==="published"?"Content published.":"Draft saved.")}
  function rememberSelection(){const selection=window.getSelection();if(!selection?.rangeCount||!rich.current)return;const range=selection.getRangeAt(0);if(rich.current.contains(range.commonAncestorContainer))savedRange.current=range.cloneRange()}
  function restoreSelection(){if(!savedRange.current)return;const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(savedRange.current)}
  function command(name:string,value?:string){rich.current?.focus();restoreSelection();document.execCommand(name,false,value);rememberSelection();setDirty(true)}
  function escaped(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function mediaMarkup(media:MediaItem){const caption=escaped(media.caption||"");return media.mimeType.startsWith("video/")?`<figure><video controls preload="metadata" src="${escaped(media.url)}"></video>${caption?`<figcaption>${caption}</figcaption>`:""}</figure><p><br></p>`:`<figure><img src="${escaped(media.url)}" alt="${escaped(media.altText||"")}">${caption?`<figcaption>${caption}</figcaption>`:""}</figure><p><br></p>`}
  function placeMedia(media:MediaItem,placement=mediaPlacement){const markup=mediaMarkup(media);if(placement==="cursor"){command("insertHTML",markup);return}if(!rich.current)return;const current=rich.current.innerHTML;if(placement==="top")rich.current.innerHTML=markup+current;else if(placement==="bottom")rich.current.innerHTML=current+markup;else{const paragraphEnd=current.indexOf("</p>");rich.current.innerHTML=paragraphEnd>=0?current.slice(0,paragraphEnd+4)+markup+current.slice(paragraphEnd+4):current+markup}setDirty(true)}
  function insertMedia(){const media=editorMedia.find(m=>m.id===bodyMediaId);if(!media){alert("Choose a body image or video first.");return}placeMedia(media)}
  async function uploadFile(form:FormData){const response=await fetch("/api/admin/media",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);const all=(result.media as MediaItem[]).filter(media=>/^(image|video)\//.test(media.mimeType));setEditorMedia(all);return all.find(media=>media.id===result.id)??null}
  async function uploadAndInsert(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setUploadingMedia(true);const form=e.currentTarget;try{const uploaded=await uploadFile(new FormData(form));if(uploaded)placeMedia(uploaded);form.reset()}catch(error){alert(error instanceof Error?error.message:"Upload failed.")}finally{setUploadingMedia(false)}}
  async function uploadDroppedFiles(files:File[]){const visual=files.filter(file=>/^(image|video)\//.test(file.type));if(!visual.length)return;setUploadingMedia(true);try{for(const file of visual){const form=new FormData();form.set("file",file);form.set("altText",file.type.startsWith("image/")?"Pasted image":"Pasted video");const uploaded=await uploadFile(form);if(uploaded)placeMedia(uploaded,"cursor")}}catch(error){alert(error instanceof Error?error.message:"Upload failed.")}finally{setUploadingMedia(false)}}
  async function uploadCover(file?:File){if(!file)return;setUploadingMedia(true);try{const form=new FormData();form.set("file",file);form.set("altText",`${item.title||"Article"} cover image`);form.set("caption","Article cover");const uploaded=await uploadFile(form);if(uploaded)patch("featuredImageId",uploaded.id)}catch(error){alert(error instanceof Error?error.message:"Upload failed.")}finally{setUploadingMedia(false)}}
  function selectDropPoint(event:React.DragEvent<HTMLDivElement>){const documentWithCaret=document as Document&{caretRangeFromPoint?:(x:number,y:number)=>Range|null;caretPositionFromPoint?:(x:number,y:number)=>{offsetNode:Node;offset:number}|null};const position=documentWithCaret.caretPositionFromPoint?.(event.clientX,event.clientY);const range=position?document.createRange():documentWithCaret.caretRangeFromPoint?.(event.clientX,event.clientY)??null;if(position&&range)range.setStart(position.offsetNode,position.offset);if(range){range.collapse(true);savedRange.current=range}}
  function patchSpecific(key:string,value:string){setSpecific(current=>({...current,[key]:value}));setDirty(true)}
  const coverMedia=editorMedia.find(media=>media.id===Number(item.featuredImageId)&&media.mimeType.startsWith("image/"));
  return <div className="editor-page">
    <div className="editor-toolbar-top"><button onClick={()=>onDone("Editor closed.")}>← Back</button><span>{saving?"Saving…":dirty?"Unsaved changes":"All changes saved"}</span><div>{item.id&&<a href={`/admin/preview/${item.id}`} target="_blank" rel="noreferrer">Preview ↗</a>}{item.status==="published"?<button onClick={()=>save("draft")}>Unpublish</button>:<button onClick={()=>save("draft")}>Save draft</button>}<button className="primary" onClick={()=>save("published")}>Publish</button></div></div>
    <div className="editor-grid"><section className="editor-canvas"><div className="type-switch">{(Object.keys(labels) as ContentType[]).map(type=><button className={item.type===type?"active":""} onClick={()=>patch("type",type)} key={type}>{labels[type]}</button>)}</div><input className="title-input" value={item.title??""} onChange={e=>patch("title",e.target.value)} placeholder="Untitled discovery"/><input className="deck-input" value={item.subtitle??""} onChange={e=>patch("subtitle",e.target.value)} placeholder="Add a subtitle or deck…"/>
      <div className="rich-toolbar" aria-label="Formatting tools"><select aria-label="Paragraph style" defaultValue="" onChange={event=>{if(event.target.value)command("formatBlock",event.target.value);event.target.value=""}}><option value="" disabled>Style</option><option value="p">Paragraph</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option><option value="blockquote">Quote</option></select><select aria-label="Font size" defaultValue="" onChange={event=>{if(event.target.value)command("fontSize",event.target.value);event.target.value=""}}><option value="" disabled>Size</option><option value="2">Small</option><option value="3">Normal</option><option value="4">Medium</option><option value="5">Large</option><option value="6">Extra large</option></select><select aria-label="Font family" defaultValue="" onChange={event=>{if(event.target.value)command("fontName",event.target.value);event.target.value=""}}><option value="" disabled>Font</option><option value="Georgia">Editorial serif</option><option value="Arial">Modern sans</option><option value="Trebuchet MS">Humanist</option><option value="Courier New">Monospace</option></select><label className="toolbar-color" title="Text color"><span>Color</span><input type="color" defaultValue="#14213d" onInput={event=>command("foreColor",event.currentTarget.value)}/></label>{[["B","bold"],["I","italic"],["U","underline"],["• List","insertUnorderedList"],["1. List","insertOrderedList"],["Left","justifyLeft"],["Center","justifyCenter"],["Right","justifyRight"],["—","insertHorizontalRule"]].map(([label,cmd])=><button type="button" onClick={()=>command(cmd)} key={label}>{label}</button>)}<button type="button" onClick={()=>{const url=prompt("Link URL");if(url)command("createLink",url)}}>Link</button><button type="button" onClick={()=>command("undo")}>Undo</button><button type="button" onClick={()=>command("redo")}>Redo</button></div>
      <p className="editor-drop-note">Paste or drag images/videos directly into the article — they upload automatically.</p><div ref={rich} className={`rich-editor ${uploadingMedia?"media-uploading":""}`} contentEditable suppressContentEditableWarning dangerouslySetInnerHTML={{__html:item.bodyHtml??""}} onInput={()=>setDirty(true)} onMouseUp={rememberSelection} onKeyUp={rememberSelection} onFocus={rememberSelection} onPaste={event=>{rememberSelection();const files=Array.from(event.clipboardData.files);if(files.some(file=>/^(image|video)\//.test(file.type))){event.preventDefault();void uploadDroppedFiles(files)}}} onDragOver={event=>{if(Array.from(event.dataTransfer.items).some(entry=>entry.kind==="file"))event.preventDefault()}} onDrop={event=>{const files=Array.from(event.dataTransfer.files);if(files.some(file=>/^(image|video)\//.test(file.type))){event.preventDefault();selectDropPoint(event);void uploadDroppedFiles(files)}}}/></section>
      <aside className="editor-settings"><EditorGroup title="Publishing"><div className="auto-slug"><strong>Automatic slug</strong><code>/{slugify(item.title??"")||"generated-from-title"}</code></div><label>Category<select value={item.categoryId??""} onChange={e=>patch("categoryId",Number(e.target.value)||null)}><option value="">Uncategorized</option>{data.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="check"><input type="checkbox" checked={Boolean(item.featured)} onChange={e=>patch("featured",e.target.checked)}/> Featured / pinned</label></EditorGroup>
        <EditorGroup title="Body media"><p className="field-note">Click inside the article first, then paste or drag an image/video there. It uploads and appears at that exact position automatically.</p><label>Placement for library media<select value={mediaPlacement} onChange={e=>setMediaPlacement(e.target.value as typeof mediaPlacement)}><option value="cursor">At the editing cursor</option><option value="top">Top of article</option><option value="after-first">After first paragraph</option><option value="bottom">Bottom of article</option></select></label><label>Choose from media library<select value={bodyMediaId??""} onChange={e=>setBodyMediaId(Number(e.target.value)||null)}><option value="">Choose image or video</option>{editorMedia.map(m=><option value={m.id} key={m.id}>{m.fileName}</option>)}</select></label><button type="button" className="secondary-button" onClick={insertMedia}>Place selected media</button><details className="manual-media-upload"><summary>Or upload with caption and alt text</summary><form className="editor-media-upload" onSubmit={uploadAndInsert}><label>Image or video<input name="file" type="file" accept="image/*,video/*" required/></label><label>Alt text<input name="altText" placeholder="Describe the image"/></label><label>Caption<input name="caption" placeholder="Optional caption"/></label><button className="primary" disabled={uploadingMedia}>{uploadingMedia?"Uploading…":"Upload & place media"}</button></form></details></EditorGroup>
        <EditorGroup title="Article cover image"><p className="field-note">The cover is separate from images inside the article. Choose any image and control its crop and focal point.</p><div className={`cover-editor-preview cover-${specific.coverRatio||"landscape"}`}>{coverMedia?<img src={coverMedia.url} alt="" style={{objectFit:(specific.coverFit||"cover") as "cover"|"contain",objectPosition:specific.coverPosition||"50% 50%"}}/>:<span>NO COVER IMAGE</span>}</div><label>Cover image<select value={item.featuredImageId??""} onChange={e=>patch("featuredImageId",Number(e.target.value)||null)}><option value="">None</option>{editorMedia.filter(media=>media.mimeType.startsWith("image/")).map(media=><option value={media.id} key={media.id}>{media.fileName}</option>)}</select></label><label className="asset-upload-button"><input type="file" accept="image/*" disabled={uploadingMedia} onChange={event=>{void uploadCover(event.target.files?.[0]);event.target.value=""}}/><span>{uploadingMedia?"Uploading…":"Upload a new cover image"}</span></label><label>Focal point<select value={specific.coverPosition||"50% 50%"} onChange={e=>patchSpecific("coverPosition",e.target.value)}><option value="50% 50%">Center</option><option value="50% 0%">Top</option><option value="50% 100%">Bottom</option><option value="0% 50%">Left</option><option value="100% 50%">Right</option></select></label><div className="form-two"><label>Image fit<select value={specific.coverFit||"cover"} onChange={e=>patchSpecific("coverFit",e.target.value)}><option value="cover">Crop to fill</option><option value="contain">Show full image</option></select></label><label>Frame<select value={specific.coverRatio||"landscape"} onChange={e=>patchSpecific("coverRatio",e.target.value)}><option value="wide">Wide 2:1</option><option value="landscape">Landscape 16:9</option><option value="portrait">Portrait 4:5</option><option value="natural">Natural height</option></select></label></div></EditorGroup>
        <EditorGroup title="Tags"><div className="tag-picker">{data.tags.map(t=><label className="check" key={t.id}><input type="checkbox" checked={item.tagIds.includes(t.id)} onChange={e=>patch("tagIds",e.target.checked?[...item.tagIds,t.id]:item.tagIds.filter(id=>id!==t.id))}/>{t.name}</label>)}</div></EditorGroup><SpecificFields type={item.type as ContentType} values={specific} setValues={v=>{setSpecific(v);setDirty(true)}}/><EditorGroup title="Excerpt & SEO"><label>Excerpt<textarea value={item.excerpt??""} onChange={e=>patch("excerpt",e.target.value)} rows={4}/></label><label>SEO title<input value={item.seoTitle??""} onChange={e=>patch("seoTitle",e.target.value)}/></label><label>SEO description<textarea value={item.seoDescription??""} onChange={e=>patch("seoDescription",e.target.value)} rows={3}/></label></EditorGroup></aside>
    </div>
  </div>
}
function EditorGroup({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="editor-group"><legend>{title}</legend>{children}</fieldset>}
function SpecificFields({type,values,setValues}:{type:ContentType;values:Record<string,string>;setValues:(v:Record<string,string>)=>void}){const fields=type==="film"?[["director","Director"],["year","Year"],["country","Country"],["rating","Rating / score"],["genre","Genre"]]:type==="place"?[["location","Location"],["country","Country"],["city","City"],["address","Address"],["website","Website"],["coordinates","Map coordinates"],["personalNotes","Personal notes"]]:[["source","Source / reference"]];return <EditorGroup title={`${labels[type]} details`}>{fields.map(([key,label])=><label key={key}>{label}<input value={values[key]??""} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}</EditorGroup>}

function MediaManager({media,onChange}:{media:MediaItem[];onChange:(m:string)=>Promise<void>}){const [uploading,setUploading]=useState(false);async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setUploading(true);const r=await fetch("/api/admin/media",{method:"POST",body:new FormData(e.currentTarget)});const j=await r.json();setUploading(false);if(!r.ok){alert(j.error);return}e.currentTarget.reset();await onChange("Media uploaded.")}return <div className="admin-content"><form className="upload-panel" onSubmit={upload}><div><h2>Upload media</h2><p>Images 25 MB · videos 250 MB · fonts 5 MB</p></div><label className="file-drop"><input name="file" type="file" accept="image/*,video/*,.woff,.woff2,font/woff,font/woff2" required/><span>Choose image, video, or font</span></label><input name="altText" placeholder="Alt text (required for meaningful images)"/><input name="caption" placeholder="Caption"/><button className="primary" disabled={uploading}>{uploading?"Uploading…":"Upload"}</button></form><div className="media-grid">{media.map(m=><figure key={m.id}>{m.mimeType.startsWith("image/")?<img src={m.url} alt={m.altText}/>:m.mimeType.startsWith("video/")?<video src={m.url} controls/>:<div className="font-file-card"><span>Aa</span><strong>WEB FONT</strong></div>}<figcaption><strong>{m.fileName}</strong><span>{formatBytes(m.size)} · used {m.usageCount??0} time(s)</span><p>{m.altText||m.caption||"No description"}</p><button className="danger" onClick={async()=>{if(!confirm("Delete this media file?"))return;const r=await fetch(`/api/admin/media?id=${m.id}`,{method:"DELETE"});const j=await r.json();if(!r.ok){alert(j.error);return}await onChange("Media deleted.")}}>Delete</button></figcaption></figure>)}</div></div>}
function formatBytes(size:number){return size>1024*1024?`${(size/1024/1024).toFixed(1)} MB`:`${Math.ceil(size/1024)} KB`}

function TaxonomyManager({categories,tags,onChange}:{categories:Category[];tags:Tag[];onChange:(m:string)=>Promise<void>}){return <div className="admin-content taxonomy-grid"><TaxonomyForm kind="categories" items={categories} onChange={onChange}/><TaxonomyForm kind="tags" items={tags} onChange={onChange}/></div>}
function TaxonomyForm({kind,items,onChange}:{kind:"categories"|"tags";items:Array<Category|Tag>;onChange:(m:string)=>Promise<void>}){const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setBusy(true);const element=e.currentTarget;const form=new FormData(element);const r=await fetch(`/api/admin/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error);return}element.reset();await onChange(`${kind==="categories"?"Category":"Tag"} saved.`)}return <section className="admin-panel taxonomy-panel"><h2>{kind[0].toUpperCase()+kind.slice(1)}</h2><form onSubmit={submit}>{error&&<p className="form-error" role="alert">{error}</p>}<p className="field-note">The slug is generated automatically from the name.</p><label>Name<input name="name" placeholder={kind==="categories"?"e.g. Design":"e.g. Bangkok"} required/></label>{kind==="categories"&&<><label>Description<input name="description" placeholder="What belongs in this category?"/></label><label>Accent color<input name="color" type="color" defaultValue="#f06f5f"/></label></>}<button className="primary" disabled={busy}>{busy?"Saving…":`Add ${kind==="categories"?"category":"tag"}`}</button></form><div className="taxonomy-list">{items.map(i=><div key={i.id}><span>{"color"in i&&<i style={{background:i.color}}/>}<strong>{i.name}</strong><small>/{i.slug}</small></span><button className="danger" onClick={async()=>{if(!confirm(`Delete ${i.name}?`))return;const r=await fetch(`/api/admin/${kind}?id=${i.id}`,{method:"DELETE"});const j=await r.json();if(!r.ok){setError(j.error);return}await onChange(`${kind} updated.`)}}>Delete</button></div>)}</div></section>}

function UsersManager(){const [users,setUsers]=useState<Array<{id:string;email:string;name:string;role:string}>>([]);useEffect(()=>{fetch("/api/admin/users").then(r=>r.json()).then(j=>setUsers(j.users??[]))},[]);async function invite(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const j=await r.json();if(!r.ok){alert(j.error);return}location.reload()}return <div className="admin-content"><section className="admin-panel users-panel"><h2>Editors & administrators</h2><form onSubmit={invite}><input name="name" placeholder="Name"/><input name="email" type="email" placeholder="ChatGPT account email" required/><select name="role"><option value="editor">Editor</option><option value="admin">Admin</option></select><button className="primary">Add user</button></form>{users.map(u=><div className="user-row" key={u.id}><div className="avatar">{u.name.slice(0,1)}</div><span><strong>{u.name}</strong><small>{u.email}</small></span><em>{u.role}</em></div>)}</section></div>}
function icon(section:Section){return{dashboard:"◫",content:"▤",media:"▧",taxonomy:"◇",design:"◈",settings:"⚙",users:"◎"}[section]}
