"use client";
/* eslint-disable @next/next/no-img-element */

import { useState, type FormEvent } from "react";
import { normalizeSiteSettings } from "@/lib/site-settings";
import type { MediaItem } from "@/lib/types";

const navigationDestinations=[{label:"Homepage",href:"/"},{label:"Philosophy section",href:"/#manifesto"},{label:"Learning archive",href:"/#archive"},{label:"All articles",href:"/articles"},{label:"All notes",href:"/notes"},{label:"All films",href:"/films"},{label:"All places",href:"/places"},{label:"Search",href:"/search"}] as const;
const destinationValue=(href:string)=>navigationDestinations.some(item=>item.href===href)?href:"custom";

export function SettingsManager({settings,media,canEdit,onSaved}:{settings:Record<string,unknown>;media:MediaItem[];canEdit:boolean;onSaved:()=>Promise<void>}){
  const initial=normalizeSiteSettings(settings.site);const [name,setName]=useState(initial.name);const [description,setDescription]=useState(initial.description);const [footer,setFooter]=useState(initial.footer);const [analytics,setAnalytics]=useState(initial.analytics);const [navigation,setNavigation]=useState(initial.navigation);const [assets,setAssets]=useState(media.filter(item=>item.mimeType.startsWith("image/")));const [logoMediaId,setLogoMediaId]=useState<number|null>(initial.logoMediaId);const [socialImageMediaId,setSocialImageMediaId]=useState<number|null>(initial.socialImageMediaId);const [uploading,setUploading]=useState<"logo"|"brandcard"|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  function patchNavigation(index:number,key:"label"|"href",value:string){setNavigation(current=>current.map((link,i)=>i===index?{...link,[key]:value}:link))}
  function moveNavigation(index:number,direction:-1|1){setNavigation(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})}
  async function uploadAsset(target:"logo"|"brandcard",file?:File){if(!file)return;setError("");setUploading(target);const form=new FormData();form.set("file",file);form.set("altText",target==="logo"?`${name} logo`:`${name} social sharing card`);form.set("caption",target==="logo"?"Website logo":"Brand card");const response=await fetch("/api/admin/media",{method:"POST",body:form});const result=await response.json();setUploading(null);if(!response.ok){setError(result.error);return}const images=(result.media as MediaItem[]).filter(item=>item.mimeType.startsWith("image/"));setAssets(images);if(target==="logo")setLogoMediaId(result.id);else setSocialImageMediaId(result.id)}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setSaving(true);const response=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({name,description,footer,logoMediaId,socialImageMediaId,analytics,navigation})});const result=await response.json();setSaving(false);if(!response.ok){setError(result.error);return}await onSaved()}
  return <div className="admin-content"><form className="settings-form admin-panel settings-controller" onSubmit={submit}><div className="settings-heading"><div><span>PUBLICATION SETTINGS</span><h2>Brand, identity & navigation</h2></div><button className="primary" disabled={!canEdit||saving}>{saving?"Saving…":"Save settings"}</button></div>{!canEdit&&<p className="warning">Only administrators can change site-wide settings.</p>}{error&&<p className="form-error" role="alert">{error}</p>}
    <fieldset><legend>Publication identity</legend><label>Website name<input value={name} onChange={event=>setName(event.target.value)} disabled={!canEdit}/></label><label>Website description<textarea value={description} onChange={event=>setDescription(event.target.value)} rows={3} disabled={!canEdit}/></label><label>Footer line<input value={footer} onChange={event=>setFooter(event.target.value)} disabled={!canEdit}/></label></fieldset>
    <fieldset><legend>Logo & Brand Card</legend><p className="field-note">Upload an image here or choose one already in the media library. The Brand Card is used when your website is shared on social media.</p><div className="brand-asset-grid"><AssetControl title="Website logo" target="logo" selectedId={logoMediaId} setSelectedId={setLogoMediaId} assets={assets} uploading={uploading} onUpload={uploadAsset} disabled={!canEdit}/><AssetControl title="Social Brand Card" target="brandcard" selectedId={socialImageMediaId} setSelectedId={setSocialImageMediaId} assets={assets} uploading={uploading} onUpload={uploadAsset} disabled={!canEdit}/></div></fieldset>
    <fieldset><legend>Navigation</legend><p className="field-note">Choose a working destination. Select “Custom URL” only for an external website or another route.</p><div className="navigation-editor">{navigation.map((link,index)=><div className="navigation-row" key={index}><span>{index+1}</span><label>Label<input value={link.label} onChange={event=>patchNavigation(index,"label",event.target.value)} placeholder="Menu label"/></label><label>Destination<select value={destinationValue(link.href)} onChange={event=>patchNavigation(index,"href",event.target.value==="custom"?"https://":event.target.value)}>{navigationDestinations.map(destination=><option value={destination.href} key={destination.href}>{destination.label}</option>)}<option value="custom">Custom URL</option></select></label>{destinationValue(link.href)==="custom"&&<label className="navigation-custom-url">Custom URL<input value={link.href} onChange={event=>patchNavigation(index,"href",event.target.value)} placeholder="https://example.com"/></label>}<button type="button" disabled={index===0} onClick={()=>moveNavigation(index,-1)} aria-label="Move link up">↑</button><button type="button" disabled={index===navigation.length-1} onClick={()=>moveNavigation(index,1)} aria-label="Move link down">↓</button><button type="button" className="danger" onClick={()=>setNavigation(current=>current.filter((_,i)=>i!==index))}>Remove</button></div>)}</div><button type="button" className="secondary-button" disabled={navigation.length>=8} onClick={()=>setNavigation(current=>[...current,{label:"New link",href:"/"}])}>+ Add navigation link</button></fieldset>
    <fieldset><legend>Analytics</legend><label>Analytics configuration<textarea value={analytics} onChange={event=>setAnalytics(event.target.value)} rows={3} placeholder="Provider ID or safe configuration" disabled={!canEdit}/></label></fieldset>
  </form></div>
}

function AssetControl({title,target,selectedId,setSelectedId,assets,uploading,onUpload,disabled}:{title:string;target:"logo"|"brandcard";selectedId:number|null;setSelectedId:(id:number|null)=>void;assets:MediaItem[];uploading:"logo"|"brandcard"|null;onUpload:(target:"logo"|"brandcard",file?:File)=>Promise<void>;disabled:boolean}){const selected=assets.find(asset=>asset.id===selectedId);return <section className="brand-asset-control"><div className="asset-preview">{selected?<img src={selected.url} alt={selected.altText}/>:<span>{target==="logo"?"YOUR LOGO":"BRAND CARD"}</span>}</div><h3>{title}</h3><label>Choose existing image<select value={selectedId??""} onChange={event=>setSelectedId(Number(event.target.value)||null)} disabled={disabled}><option value="">Use default</option>{assets.map(asset=><option value={asset.id} key={asset.id}>{asset.fileName}</option>)}</select></label><label className="asset-upload-button"><input type="file" accept="image/*" disabled={disabled||uploading!==null} onChange={event=>onUpload(target,event.target.files?.[0])}/><span>{uploading===target?"Uploading…":"Upload new image"}</span></label></section>}
