import { deleteMedia, listMedia, runtimeEnv, saveMedia } from "@/lib/database";
import { requireApiUser } from "@/lib/auth";
import { sanitizePlain } from "@/lib/validation";
export async function GET(request:Request){const auth=await requireApiUser(request);if("response"in auth)return auth.response;return Response.json({media:await listMedia()})}
export async function POST(request:Request){
  const auth=await requireApiUser(request);if("response"in auth)return auth.response;const bucket=runtimeEnv().MEDIA;if(!bucket)return Response.json({error:"Media storage is unavailable."},{status:503});
  try{const form=await request.formData();const file=form.get("file");if(!(file instanceof File))return Response.json({error:"Choose an image or video."},{status:400});if(!/^(image|video)\//.test(file.type))return Response.json({error:"Only image and video files are supported."},{status:415});const max=file.type.startsWith("video/")?250*1024*1024:25*1024*1024;if(file.size>max)return Response.json({error:"File is too large."},{status:413});const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-120);const key=`${new Date().toISOString().slice(0,10)}-${crypto.randomUUID()}-${safeName}`;await bucket.put(key,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{originalName:file.name}});const id=await saveMedia({objectKey:key,fileName:file.name,mimeType:file.type,size:file.size,altText:sanitizePlain(form.get("altText"),300),caption:sanitizePlain(form.get("caption"),500)},auth.user.userId);return Response.json({id,media:await listMedia()},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"Upload failed."},{status:400})}
}
export async function DELETE(request:Request){const auth=await requireApiUser(request);if("response"in auth)return auth.response;try{await deleteMedia(Number(new URL(request.url).searchParams.get("id")),auth.user.userId);return Response.json({media:await listMedia()})}catch(error){return Response.json({error:error instanceof Error?error.message:"Delete failed."},{status:409})}}
