import { env } from "cloudflare:workers";
import type { Category, ContentInput, ContentItem, MediaItem, Tag } from "./types";

type RuntimeEnv = { DB: D1Database; MEDIA?: R2Bucket; ADMIN_EMAILS?: string };
export function runtimeEnv() { return env as unknown as RuntimeEnv; }
export function rawDb() { const db = runtimeEnv().DB; if (!db) throw new Error("Database is unavailable."); return db; }
let ready: Promise<void> | null = null;
export function ensureDatabase() { ready ??= initialize(); return ready; }

async function initialize() {
  const db = rawDb();
  const statements = [
    `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'editor', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '#f06f5f', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tags (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS media (id INTEGER PRIMARY KEY AUTOINCREMENT, object_key TEXT NOT NULL UNIQUE, file_name TEXT NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL, alt_text TEXT NOT NULL DEFAULT '', caption TEXT NOT NULL DEFAULT '', created_by TEXT REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS content_items (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL, title TEXT NOT NULL, slug TEXT NOT NULL, subtitle TEXT NOT NULL DEFAULT '', excerpt TEXT NOT NULL DEFAULT '', body_html TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'draft', category_id INTEGER REFERENCES categories(id), author_id TEXT REFERENCES users(id), featured_image_id INTEGER REFERENCES media(id), gallery_json TEXT NOT NULL DEFAULT '[]', fields_json TEXT NOT NULL DEFAULT '{}', seo_title TEXT NOT NULL DEFAULT '', seo_description TEXT NOT NULL DEFAULT '', social_image_id INTEGER REFERENCES media(id), featured INTEGER NOT NULL DEFAULT 0, published_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS content_tags (content_id INTEGER NOT NULL REFERENCES content_items(id) ON DELETE CASCADE, tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(content_id, tag_id))`,
    `CREATE TABLE IF NOT EXISTS related_content (content_id INTEGER NOT NULL REFERENCES content_items(id) ON DELETE CASCADE, related_id INTEGER NOT NULL REFERENCES content_items(id) ON DELETE CASCADE, PRIMARY KEY(content_id, related_id))`,
    `CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS activity (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT REFERENCES users(id), action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_content_type_slug ON content_items(type, slug)`,
    `CREATE INDEX IF NOT EXISTS idx_content_status_published ON content_items(status, published_at)`,
    `CREATE INDEX IF NOT EXISTS idx_content_category_status ON content_items(category_id, status)`,
    `CREATE INDEX IF NOT EXISTS idx_activity_created ON activity(created_at)`,
  ];
  await db.batch(statements.map((statement) => db.prepare(statement)));
  await seedExistingPublication(db);
}

async function seedExistingPublication(db: D1Database) {
  const count = await db.prepare("SELECT COUNT(*) AS total FROM content_items").first<{ total: number }>();
  if (Number(count?.total ?? 0) > 0) return;
  await db.batch([
    db.prepare("INSERT OR IGNORE INTO categories (name,slug,description,color) VALUES (?,?,?,?)").bind("ภาพยนตร์","film","ภาพยนตร์ การมอง และวัฒนธรรมจอเงิน","#f06f5f"),
    db.prepare("INSERT OR IGNORE INTO categories (name,slug,description,color) VALUES (?,?,?,?)").bind("ภาษา","language","คำ ความหมาย และเรื่องเล่าข้ามภาษา","#6c77e8"),
    db.prepare("INSERT OR IGNORE INTO tags (name,slug) VALUES (?,?)").bind("Bangkok","bangkok"),
    db.prepare("INSERT OR IGNORE INTO tags (name,slug) VALUES (?,?)").bind("Cinema","cinema"),
    db.prepare("INSERT OR IGNORE INTO tags (name,slug) VALUES (?,?)").bind("Hindi","hindi"),
    db.prepare("INSERT OR IGNORE INTO settings (key,value) VALUES (?,?)").bind("site",JSON.stringify({name:"Know Nothing Daily",description:"A personal archive of curiosity",footer:"ONE NEW THING · EVERY DAY",socialLinks:[],navigation:[{label:"แนวคิด",href:"/#manifesto"},{label:"คลังความรู้",href:"/#archive"}]})),
  ]);
  const film = await db.prepare("SELECT id FROM categories WHERE slug='film'").first<{id:number}>();
  const language = await db.prepare("SELECT id FROM categories WHERE slug='language'").first<{id:number}>();
  await db.batch([
    db.prepare(`INSERT INTO content_items (type,title,slug,subtitle,excerpt,body_html,status,category_id,fields_json,seo_title,seo_description,featured,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind("article","กรุงเทพฯ เคยเป็นฉากหนังสายลับฝรั่งเศส","bangkok-french-spy-film","OSS 117: Panic in Bangkok และเมืองไทยบนแผนที่กองถ่าย","OSS 117: Panic in Bangkok ถ่ายทำในไทยตั้งแต่ปี 1964 เป็นหลักฐานชิ้นเล็ก ๆ ว่าเมืองไทยอยู่บนแผนที่กองถ่ายนานกว่าที่คิด","<p>หนังสายลับฝรั่งเศส <em>OSS 117: Panic in Bangkok</em> เดินทางมาถ่ายทำในประเทศไทยตั้งแต่ปี 1964</p><blockquote>ประวัติศาสตร์บางครั้งซ่อนตัวอยู่ในฉากหลังของภาพยนตร์</blockquote><p>บันทึกนี้เริ่มจากคำถามง่าย ๆ ว่า กรุงเทพฯ ปรากฏในสายตาของโลกผ่านจอภาพยนตร์ตั้งแต่เมื่อไร</p>","published",film?.id??null,JSON.stringify({source:"จากการค้นคว้าเรื่องภาพยนตร์"}),"กรุงเทพฯ ในหนังสายลับฝรั่งเศส","OSS 117: Panic in Bangkok ถ่ายทำในไทยตั้งแต่ปี 1964",1,"2026-08-20T08:00:00.000Z"),
    db.prepare(`INSERT INTO content_items (type,title,slug,subtitle,excerpt,body_html,status,category_id,fields_json,seo_title,seo_description,featured,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind("note","“Yaadon Ki Baaraat” แปลว่าอะไร?","yaadon-ki-baaraat-meaning","ขบวนแห่งความทรงจำ","ชื่อภาษาฮินดีนี้หมายถึง ‘ขบวนแห่งความทรงจำ’ และยังเป็นชื่อภาพยนตร์บอลลีวูดคลาสสิกปี 1973","<p><strong>Yaadon Ki Baaraat</strong> แปลได้ว่า ‘ขบวนแห่งความทรงจำ’</p><p>คำนี้ยังเป็นชื่อภาพยนตร์บอลลีวูดปี 1973 และเป็นตัวอย่างเล็ก ๆ ว่าชื่อเรื่องหนึ่งพาเราเดินทางข้ามภาษาได้ไกลแค่ไหน</p>","published",language?.id??null,JSON.stringify({source:"จากเพลงที่ได้ฟัง"}),"Yaadon Ki Baaraat แปลว่าอะไร","ความหมายของชื่อภาษาฮินดี Yaadon Ki Baaraat",0,"2026-08-19T08:00:00.000Z"),
  ]);
}

const contentSelect = `SELECT c.id,c.type,c.title,c.slug,c.subtitle,c.excerpt,c.body_html AS bodyHtml,c.status,c.category_id AS categoryId,cat.name AS categoryName,cat.slug AS categorySlug,cat.color AS categoryColor,c.author_id AS authorId,u.name AS authorName,c.featured_image_id AS featuredImageId,CASE WHEN fm.object_key IS NOT NULL THEN '/media/'||fm.object_key ELSE NULL END AS featuredImageUrl,fm.alt_text AS featuredImageAlt,fm.mime_type AS featuredImageMime,c.gallery_json AS galleryJson,c.fields_json AS fieldsJson,c.seo_title AS seoTitle,c.seo_description AS seoDescription,c.social_image_id AS socialImageId,c.featured,c.published_at AS publishedAt,c.created_at AS createdAt,c.updated_at AS updatedAt FROM content_items c LEFT JOIN categories cat ON cat.id=c.category_id LEFT JOIN users u ON u.id=c.author_id LEFT JOIN media fm ON fm.id=c.featured_image_id`;

export async function listContent(options: {publishedOnly?:boolean;type?:string;search?:string;category?:string;tag?:string;limit?:number}={}) {
  await ensureDatabase(); const clauses:string[]=[]; const values:unknown[]=[];
  if(options.publishedOnly)clauses.push("c.status='published'"); if(options.type){clauses.push("c.type=?");values.push(options.type)}
  if(options.search){clauses.push("(c.title LIKE ? OR c.subtitle LIKE ? OR c.excerpt LIKE ? OR c.body_html LIKE ?)");const q=`%${options.search}%`;values.push(q,q,q,q)}
  if(options.category){clauses.push("cat.slug=?");values.push(options.category)} if(options.tag){clauses.push("EXISTS (SELECT 1 FROM content_tags ct JOIN tags t ON t.id=ct.tag_id WHERE ct.content_id=c.id AND t.slug=?)");values.push(options.tag)}
  const where=clauses.length?` WHERE ${clauses.join(" AND ")}`:""; return (await rawDb().prepare(`${contentSelect}${where} ORDER BY c.featured DESC,COALESCE(c.published_at,c.updated_at) DESC LIMIT ?`).bind(...values,Math.min(options.limit??100,500)).all<ContentItem>()).results;
}
export async function getContentById(id:number,publishedOnly=false){await ensureDatabase();const item=await rawDb().prepare(`${contentSelect} WHERE c.id=?${publishedOnly?" AND c.status='published'":""}`).bind(id).first<ContentItem>();return item?attachTags(item):null}
export async function getContentBySlug(type:string,slug:string){await ensureDatabase();const item=await rawDb().prepare(`${contentSelect} WHERE c.type=? AND c.slug=? AND c.status='published'`).bind(type,slug).first<ContentItem>();return item?attachTags(item):null}
async function attachTags(item:ContentItem){item.tags=(await rawDb().prepare("SELECT t.id,t.name,t.slug FROM tags t JOIN content_tags ct ON ct.tag_id=t.id WHERE ct.content_id=? ORDER BY t.name").bind(item.id).all<Tag>()).results;return item}

export async function createContent(input:ContentInput,userId:string){await ensureDatabase();const db=rawDb();const result=await db.prepare(`INSERT INTO content_items (type,title,slug,subtitle,excerpt,body_html,status,category_id,author_id,featured_image_id,gallery_json,fields_json,seo_title,seo_description,social_image_id,featured,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(input.type,input.title,input.slug,input.subtitle,input.excerpt,input.bodyHtml,input.status,input.categoryId,userId,input.featuredImageId,input.galleryJson,input.fieldsJson,input.seoTitle,input.seoDescription,input.socialImageId,input.featured?1:0,input.status==="published"?new Date().toISOString():null).run();const id=Number(result.meta.last_row_id);await replaceTags(db,id,input.tagIds);await logActivity(userId,"created",input.type,String(id),input.title);return getContentById(id)}
export async function updateContent(id:number,input:ContentInput,userId:string){await ensureDatabase();const db=rawDb();await db.prepare(`UPDATE content_items SET type=?,title=?,slug=?,subtitle=?,excerpt=?,body_html=?,status=?,category_id=?,author_id=?,featured_image_id=?,gallery_json=?,fields_json=?,seo_title=?,seo_description=?,social_image_id=?,featured=?,published_at=CASE WHEN ?='published' THEN COALESCE(published_at,CURRENT_TIMESTAMP) ELSE NULL END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(input.type,input.title,input.slug,input.subtitle,input.excerpt,input.bodyHtml,input.status,input.categoryId,userId,input.featuredImageId,input.galleryJson,input.fieldsJson,input.seoTitle,input.seoDescription,input.socialImageId,input.featured?1:0,input.status,id).run();await replaceTags(db,id,input.tagIds);await logActivity(userId,input.status==="published"?"published":"updated",input.type,String(id),input.title);return getContentById(id)}
async function replaceTags(db:D1Database,id:number,tagIds:number[]){await db.prepare("DELETE FROM content_tags WHERE content_id=?").bind(id).run();if(tagIds.length)await db.batch(tagIds.map(tagId=>db.prepare("INSERT OR IGNORE INTO content_tags (content_id,tag_id) VALUES (?,?)").bind(id,tagId)))}
export async function deleteContent(id:number,userId:string){const item=await getContentById(id);if(!item)return false;await rawDb().prepare("DELETE FROM content_items WHERE id=?").bind(id).run();await logActivity(userId,"deleted",item.type,String(id),item.title);return true}

export async function listCategories(){await ensureDatabase();return(await rawDb().prepare("SELECT id,name,slug,description,color FROM categories ORDER BY name").all<Category>()).results}
export async function listTags(){await ensureDatabase();return(await rawDb().prepare("SELECT id,name,slug FROM tags ORDER BY name").all<Tag>()).results}
export async function saveTaxonomy(kind:"categories"|"tags",value:{name:string;slug:string;description?:string;color?:string}){await ensureDatabase();if(kind==="categories")return rawDb().prepare("INSERT INTO categories (name,slug,description,color) VALUES (?,?,?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,color=excluded.color").bind(value.name,value.slug,value.description??"",value.color??"#f06f5f").run();return rawDb().prepare("INSERT INTO tags (name,slug) VALUES (?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name").bind(value.name,value.slug).run()}
export async function deleteTaxonomy(kind:"categories"|"tags",id:number){await ensureDatabase();return rawDb().prepare(`DELETE FROM ${kind} WHERE id=?`).bind(id).run()}

export async function listMedia(){await ensureDatabase();return(await rawDb().prepare("SELECT m.id,m.object_key AS objectKey,m.file_name AS fileName,m.mime_type AS mimeType,m.size,m.alt_text AS altText,m.caption,m.created_at AS createdAt,'/media/'||m.object_key AS url,(SELECT COUNT(*) FROM content_items c WHERE c.featured_image_id=m.id OR c.social_image_id=m.id) AS usageCount FROM media m ORDER BY m.created_at DESC LIMIT 250").all<MediaItem>()).results}
export async function getMediaById(id:number|null){if(!id)return null;await ensureDatabase();return rawDb().prepare("SELECT m.id,m.object_key AS objectKey,m.file_name AS fileName,m.mime_type AS mimeType,m.size,m.alt_text AS altText,m.caption,m.created_at AS createdAt,'/media/'||m.object_key AS url FROM media m WHERE m.id=?").bind(id).first<MediaItem>()}
export async function saveMedia(meta:{objectKey:string;fileName:string;mimeType:string;size:number;altText:string;caption:string},userId:string){await ensureDatabase();const r=await rawDb().prepare("INSERT INTO media (object_key,file_name,mime_type,size,alt_text,caption,created_by) VALUES (?,?,?,?,?,?,?)").bind(meta.objectKey,meta.fileName,meta.mimeType,meta.size,meta.altText,meta.caption,userId).run();await logActivity(userId,"uploaded","media",String(r.meta.last_row_id),meta.fileName);return Number(r.meta.last_row_id)}
export async function deleteMedia(id:number,userId:string){await ensureDatabase();const media=await rawDb().prepare("SELECT object_key AS objectKey,file_name AS fileName FROM media WHERE id=?").bind(id).first<{objectKey:string;fileName:string}>();if(!media)return null;const usage=await rawDb().prepare("SELECT COUNT(*) AS total FROM content_items WHERE featured_image_id=? OR social_image_id=?").bind(id,id).first<{total:number}>();const settingsUsage=await rawDb().prepare("SELECT COUNT(*) AS total FROM settings WHERE value LIKE ?").bind(`%${media.objectKey}%`).first<{total:number}>();if(Number(usage?.total??0)>0||Number(settingsUsage?.total??0)>0)throw new Error("This media item is still in use.");await runtimeEnv().MEDIA?.delete(media.objectKey);await rawDb().prepare("DELETE FROM media WHERE id=?").bind(id).run();await logActivity(userId,"deleted","media",String(id),media.fileName);return media}

export async function getSettings(){await ensureDatabase();const rows=(await rawDb().prepare("SELECT key,value FROM settings").all<{key:string;value:string}>()).results;return Object.fromEntries(rows.map(r=>{try{return[r.key,JSON.parse(r.value)]}catch{return[r.key,r.value]}}))}
export async function saveSetting(key:string,value:unknown,userId:string){await ensureDatabase();await rawDb().prepare("INSERT INTO settings (key,value,updated_at) VALUES (?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(key,JSON.stringify(value)).run();await logActivity(userId,"updated","settings",key,key)}
export async function dashboardData(){await ensureDatabase();const counts=(await rawDb().prepare("SELECT type,status,COUNT(*) AS total FROM content_items GROUP BY type,status").all<{type:string;status:string;total:number}>()).results;const activity=(await rawDb().prepare("SELECT a.id,a.action,a.entity_type AS entityType,a.detail,a.created_at AS createdAt,u.name AS userName FROM activity a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 12").all<{id:number;action:string;entityType:string;detail:string;createdAt:string;userName?:string}>()).results;return{counts,activity}}
export async function logActivity(userId:string,action:string,entityType:string,entityId:string,detail:string){await rawDb().prepare("INSERT INTO activity (user_id,action,entity_type,entity_id,detail) VALUES (?,?,?,?,?)").bind(userId,action,entityType,entityId,detail).run()}
